"""Bundle the dependency-free portal into a C++ header for ESPHome."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PORTAL = ROOT / "portal"
OUTPUT = ROOT / "components" / "inovolt_portal" / "portal_data.h"
ASSETS = {
    "INOVOLT_PORTAL_INDEX": ("index.html", "text/html; charset=utf-8"),
    "INOVOLT_PORTAL_CSS": ("styles.css", "text/css; charset=utf-8"),
    "INOVOLT_PORTAL_APP": ("app.js", "text/javascript; charset=utf-8"),
    "INOVOLT_PORTAL_CORE": ("core.mjs", "text/javascript; charset=utf-8"),
}


def main() -> None:
    lines = [
        "#pragma once",
        "",
        "// Generated by scripts/build_portal_header.py. Do not edit manually.",
        "#ifdef USE_ESP32",
        "",
        "namespace esphome::inovolt_portal {",
        "",
        "// clang-format off",
    ]
    for symbol, (filename, content_type) in ASSETS.items():
        content = (PORTAL / filename).read_text(encoding="utf-8")
        lines.extend(
            [
                f'static constexpr const char *{symbol}_TYPE = "{content_type}";',
                f'static constexpr const char {symbol}[] = R"INOVOLT_PORTAL({content})INOVOLT_PORTAL";',
                "",
            ]
        )
    lines.extend(
        ["// clang-format on", "", "}  // namespace esphome::inovolt_portal", "", "#endif", ""]
    )
    OUTPUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
